baseURL: 'https://story.kotoblog.pp.ua/'
languageCode: 'en-us'
title: 'Serhii Polishchuk'
theme: 'hugo-theme-texify'
ignoreErrors: ["error-remote-getjson"]
#relativeURLs: true
markup:
  highlight:
    noClasses: false
